### ISSUE TITLE
setup meteor with nbserverproxy

### ISSUE THREAD

**Issue by kmader** [4QuantOSS/ohif_binder#1]
https://github.com/jupyterhub/nbserverproxy

```
jupyter serverextension enable nbrsessionproxy --sys-prefix && \
jupyter nbextension install --py nbrsessionproxy --sys-prefix && \
jupyter nbextension enable --py nbrsessionproxy --sys-prefix
```

https://github.com/jupyter/repo2docker/pull/239/files

**Comment by betatim** [comment]
You probably want to use [nbserverproxy](https://github.com/jupyterhub/nbserverproxy/) not nbrsessionproxy. (You link to it but the extension enabling code is for nbrsessionproxy)

**Comment by kmader** [comment]
yes, I just copy and pasted it from the code I found for R, in the actual environment.yaml it just installs the conda nbserverproxy

**Comment by kmader** [comment]
basic functionality works but still has issue with paths
